---
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - CUSTOM_USER=login    # Замените на имя пользователя
      - PASSWORD=password    # Замените на пароль
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - CHROME_CLI=https://google.com #optional
    volumes:
      - /root/chromium/config:/config
    ports:
      - 3010:3000   # Измените 3010 на другой порт, если нужно
      - 3011:3001   # Измените 3011 на другой порт, если нужно
    shm_size: "3gb"
    restart: unless-stopped